### ISSUE TITLE
Aboutページの導入

### ISSUE THREAD

**Issue by notchman8600** [crowd4u/crowd4u.github.io#15]
[背景]

現在、トップページには全記事のリストが表示されているだけである。サイトとしてAboutページによる説明や導線整理を行なうことで見やすいサイトを目指す。

[作業内容]
トップページに以下の内容を追加
- サイトタイトルを掲載
- Aboutとして簡単な紹介を追加
- 記事一覧のリストの前に見だしで「記事一覧」などと表示する

[懸念点]
- 細かい文言は都度調整を図る

**Comment by eniehack** [comment]
これはトップページにAboutを記載するという認識でいいですか……？
